# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

evaluation_prompt = """# Instruction

You are an expert evaluator. Your task is to evaluate the quality of a response generated by an LLM.  I will provide you with a question and an AI-generated response. You should first read the question to understand the task, and then evaluate the quality of the response based on the rules provided below.

# User question

{question}

# LLM response

{response}

# Evaluation

## Rubric

{rubric}

## Rules

### Output format

Return a JSON list of every rubric element:
- Each element must contain the original 'id' and 'criterion' exactly as it appears in the original rubric.
- Add a new 'explanation' field containing a brief (maximum 20 words) plain text explanation of why the criterion was or wasn't met (using quotes from the answer when possible).
- Add a new 'decision' field containing a 'yes' or 'no' indicating whether or not the criterion was met.
- Omit the 'points' and 'at_beginning' fields from the original rubric.

### Decisions

Here are some instructions to guide how to determine if certain criteria are met.

- If a criterion starts with "States that" then it should be met only if the response is fairly explicit in stating what follows. If instead the criterion starts with "States or implies that" then it can be met even if the response is less explicit.

- If the criterion "The most important information is at the beginning" is present, it must be guided solely by the criteria in the rubric for which 'at_beginning' is true. If either (1) *all* of these criteria where the 'points' field is 5 or (2) *any* of these criteria where the 'points' field is -5 are met within the first paragraph of the response (or the first two paragraphs if the first paragraph is 1-2 sentences), then this criterion is met. If they are not, then the criterion is unmet even if the information in the first 1-2 paragraphs is important and relevant.

- The criterion "Gives more information than warranted by the question" should be met by a response that exhibits one or more of the following issues. This must happen even if the information in the response is helpful, relevant, and appropriate.
    - The response provides more detailed information than needed to resolve the core question(s). For example, if a question asks for a feature that isn't available on a given platform, the response gives detailed information about other (unrelated) features that are available rather than simply stating the unavailability of the desired feature.
    - The response provides superfluous examples. For example, if a question asks about encountering content moderation on a platform, the response provides many examples of sentences or phrases that would be blocked by the platform.
    - The response provides "laundry lists" of options or factors rather than focusing on what is most relevant.
    - The response spends significant time speculating on what might have happened (e.g., how a user wound up in a given situation), what a person might be thinking or doing, or what might happen next.
    - The same information is restated multiple times without additional nuance.

- The criterion "Gives more action items than warranted by the question" should be met by a response that exhibits one or more of the following issues. This must happen even if the action items are helpful, relevant, and appropriate.
    - The response suggests actions that are relevant only in hypothetical future scenarios, or that are only tangentially related to the core question(s).
    - The response suggests more than 1-2 short and relevant actions even though the question is purely seeking information (e.g., asking "What's going on?" or "Why did this happen?").
    The exception is when these actions prevent likely immediate or future harm; e.g., the question indicates that the user is being scammed and the response provides actions to prevent further financial loss, or the question indicates the likely presence of malware on a user's device and the response provides actions to check for malware.
    - Some provided actions are redundant given the context of the question, or the overall list of actions is too complex or time-consuming relative to the question, even if each individual action is relevant and useful. For example, the response tells someone being harassed to collect detailed evidence, block the harassing accounts, report them to multiple platforms for multiple offenses, contact law enforcement, find a lawyer, and reach out to one or multiple support organizations.

- The criterion "Overstates the effectiveness or ineffectiveness of certain approaches" should be met only by responses that are explicit and precise in commenting on the effectiveness of solutions they propose; e.g, saying things like "This works for 85% of users" or "This is guaranteed to work". It should not be met by responses that make less precise comments like "This is unlikely to work" or "This works in most cases", and it must not be met by responses that provide ineffective solutions but make no explicit comments about how well these solutions work.

# Final instruction

Return just the JSON object. Do not include any other text in the response."""
